### ISSUE TITLE
Test for MTKPCommandQueueUser

### ISSUE THREAD

**Issue by schulz0r** [LRH539/MetalKitPlus#10]
It has to be ensured that the extension for the protocol MTKPCommandQueueUser works properly. For that purpose, there has to be a test.

**Comment by claudio-vellage** [comment]
Please reference your pull requests in your issues so that it becomes obvious that you've already worked on this and possibly solved this issue. #12

**Comment by claudio-vellage** [comment]
I just reviewed #12, but that pull request changes multiple things at once.
