### ISSUE TITLE
tgSize of MTKPShader needs to be optional

### ISSUE THREAD

**Issue by schulz0r** [LRH539/MetalKitPlus#13]
Some algorithms require the threadgroup size to be set as a multiple of the thread execution width. You can query this parameter from a MTLComputePipelineState. By now, an MTKPShader requires the tgSize to be known in advance, before the MTKPShader is added to the asset dictionary. Thus, the initialization of a MTKPShader with the correct tgSize is not possible in given situation and dummy values must be used.
I would suggest to make tgSize an optional and to set its default argument to nil. Later, in the execute function of the MTKPComputer, it should be set correctly by the user.

**Comment by claudio-vellage** [comment]
The tgSize already has a default argument, so you don't necessarily have to set the tgSize in advance. If this argument would be set to nil, the shader couldn't be executed if no tgSize is provided and thus would probably result in a crash.

That is, unless the code included a guard statement which would use a fallback value for the tgSize, which would be equivalent to just setting the tgSize to a sane default.
