### ISSUE TITLE
Cannot load textures, because MTKPShaderIO.textureLoader is not visible to the user.

### ISSUE THREAD

**Issue by schulz0r** [LRH539/MetalKitPlus#2]
MTKPShaderIO.textureLoader is an internal property. Thus it can be accessed inside the defining module (the framework), but not in a project where MTKP is an imported module.
Same applies to MTKPComputer.assets.

**Comment by claudio-vellage** [comment]
In what situation do you need direct access to these properties?

**Comment by schulz0r** [comment]
In my project, I have a class ResponseEstimationIO, which is a subclass of MTKPShaderIO. I want to use the textureLoader to load input images as textures for my shader. When trying to access the loader in the initializer of my subclass, an compiler error occures saying that the loader is not accessible because of its internal access level.

Edit: The swift documentation describes exactly this:
"Internal access enables entities to be used within any source file from their defining module, but not in any source file outside of that module. You typically use internal access when defining an app’s or a framework’s internal structure."

**Comment by claudio-vellage** [comment]
The relevant code section has been removed from the repository. MTKPShaderIO should no longer be used. Use MTKPIOProvider instead and extend MTKPTextureLoader. You should define your own MTKTextureLoader which you can use within fetchTextures.

I'm not sure what's the issue with assets and why you need direct access to them. If the problem persists, please open a new issue and clarify your problem.
